name: Build Minecraft Fabric Mod JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 21 (OpenLogic)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptium'  # Use Adoptium for OpenJDK
          java-package: jdk

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Minecraft Fabric Mod
        run: ./gradlew --refresh-dependencies

      - name: Build the mod with Gradle
        run: ./gradlew build

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: fabric-mod-jar
          path: build/libs/*.jar
